### ISSUE TITLE
Overall Site Style

### ISSUE THREAD

**Issue by aarowill** [squeegee-whiteboard/client#16]
Enforce a nice color pattern and certain other things like font/font sizes and what not so the site is consistent. Preferably use a CSS framework to cut down on actual legwork. My personal CSS frameworks of interest right now include:

* [Materialize](https://materializecss.com/)
* [Pure](https://purecss.io/)
* [Bulma](https://bulma.io/)

Some others potentially worth looking at for discussion points are:

* [Bootstrap](https://getbootstrap.com/)
* [UIkit](https://getuikit.com/)
* [Foundation](https://foundation.zurb.com/sites/docs/v/5.5.3/css.html)
* [Semantic UI](https://semantic-ui.com/)

Also worth thinking about how these different frameworks interact with React. I haven't looked into that too much yet.

**Comment by vkirch** [comment]
We are moving forward with materialize.
